import Link from "next/link";
import { classes, subjects } from "../class-data/subjects";

export default function HomePage() { return <main>
  <section className="hero"><div className="wrap hero-grid"><div><span className="eyebrow">SeekaNepal · Learn. Ask. Understand.</span><h1>Your AI Teacher. Your Learning Journey.</h1><p>Learn any subject with step-by-step guidance, ask follow-up questions, practice at your pace and understand why an answer works.</p><div className="actions"><Link className="button" href="/learn">Start learning</Link><Link className="button alt" href="#subjects">Explore subjects</Link></div></div><div className="hero-card"><span className="eyebrow" style={{ color: "#4de1c1" }}>AI tutor preview</span><h2>Let’s learn one idea at a time.</h2><div className="chat"><div className="bubble student">Can you explain force and motion simply?</div><div className="bubble ai">Of course. Imagine pushing a football. The push is a force, and the ball’s movement is motion. Want to try an example?</div><div className="bubble student">Yes, give me a practice question.</div></div></div></div></section>
  <section className="section" id="subjects"><div className="wrap"><div className="section-title"><div><span className="eyebrow">Choose your next step</span><h2>Learn across every subject</h2></div><Link href="/learn">See all classes →</Link></div><div className="cards">{subjects.map((subject) => <Link className="card" href={`/class-7/${subject.slug}`} key={subject.slug}><span className="subject-icon" style={{ background: subject.color }}>{subject.icon}</span><h3>{subject.name}</h3><p>{subject.description}</p></Link>)}</div></div></section>
  <section className="section"><div className="wrap"><div className="section-title"><div><span className="eyebrow">Nepal-focused learning</span><h2>Pick your class</h2></div><p className="muted">Class 1 through Class 12</p></div><div className="class-grid">{classes.map((c) => <Link className="class-pill" href={`/class-${c}`} key={c}>Class {c}</Link>)}</div></div></section>
  <section className="section"><div className="wrap feature"><div className="card"><span className="feature-number">01 · EXPLAIN</span><h3>Understand, don’t just memorize</h3><p>Ask for a simpler explanation, a new example or a hint before seeing the answer.</p></div><div className="card"><span className="feature-number">02 · PRACTICE</span><h3>Practice with purpose</h3><p>Try multiple choice, true/false, short-answer and numerical questions.</p></div><div className="card"><span className="feature-number">03 · GROW</span><h3>See your progress</h3><p>Track topics completed, areas to improve and your next recommended lesson.</p></div></div></section>
</main>; }
